/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ffb1c1",
        "on-tertiary-container": "#3c2500",
        "surface-container-highest": "#3d2d52",
        "surface-dim": "#1b0b2f",
        "surface-container-lowest": "#150529",
        "inverse-on-surface": "#39294e",
        "on-primary": "#00363a",
        "outline-variant": "#5b3f45",
        "surface-bright": "#423257",
        "surface-container-high": "#322247",
        "on-surface": "#eedcff",
        "surface-container": "#27183c",
        "on-primary-fixed-variant": "#004f54",
        "error-container": "#93000a",
        "surface-variant": "#3d2d52",
        "on-secondary-container": "#fff6f6",
        "on-background": "#eedcff",
        "on-tertiary-fixed-variant": "#633f00",
        "tertiary-fixed": "#ffddb4",
        "tertiary-fixed-dim": "#ffb955",
        "primary-fixed-dim": "#00dbe9",
        "on-primary-fixed": "#002022",
        "on-secondary": "#66002a",
        "on-secondary-fixed-variant": "#8f003e",
        secondary: "#ffb1c1",
        "on-secondary-fixed": "#3f0017",
        primary: "#00dbe9",
        "inverse-surface": "#eedcff",
        error: "#ffb4ab",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#002f33",
        "primary-container": "#00a0aa",
        "surface-tint": "#00dbe9",
        "on-error": "#690005",
        surface: "#1b0b2f",
        outline: "#ab888e",
        tertiary: "#ffb955",
        "on-tertiary-fixed": "#291800",
        background: "#1b0b2f",
        "on-tertiary": "#452b00",
        "on-surface-variant": "#e4bdc3",
        "inverse-primary": "#006970",
        "primary-fixed": "#7df4ff",
        "tertiary-container": "#c68200",
        "secondary-container": "#e00266",
        "secondary-fixed": "#ffd9df",
        "surface-container-low": "#231437",

        // Accent colors (neon palette)
        "accent-cyan": "#00f0ff",
        "accent-pink": "#ff2d7b",
        "accent-yellow": "#f8a826",
        "accent-purple": "#b44dff",
        "accent-green": "#39ff8e",
      },
      fontFamily: {
        headline: ["Newsreader"],
        body: ["Inter"],
        label: ["Space Grotesk"],
        chrome: ["Monoton"],
        display: ["Playfair Display"],
        "mono-dm": ["DM Mono"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      animation: {
        flicker: "flicker 1.5s infinite alternate",
        "star-pulse": "star-pulse 3s infinite ease-in-out",
      },
      keyframes: {
        flicker: {
          "0%, 19%, 21%, 23%, 25%, 54%, 56%, 100%": { opacity: "1" },
          "20%, 24%, 55%": { opacity: "0.8" },
        },
        "star-pulse": {
          "0%, 100%": { opacity: "0.3", transform: "scale(1)" },
          "50%": { opacity: "1", transform: "scale(1.2)" },
        },
      },
    },
  },
  plugins: [],
};
